INTENT_LABELS = [
    "FEEDING",
    "SEEK_ATTENTION",
    "WANT_PLAY",
    "WANT_DOOR_OPEN",
    "DEFENSIVE_ALERT",
    "RELAX_SLEEP",
    "CURIOUS_OBSERVE",
    "UNCERTAIN",
]

STATE_LEVELS = ["LOW", "MID", "HIGH"]
